"""empty message

Revision ID: 1b6c0d0bbdcc
Revises: 
Create Date: 2018-03-01 15:50:50.631621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6c0d0bbdcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_circles',
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], ),
    sa.PrimaryKeyConstraint('circle_id', 'friend_id')
    )
    op.add_column(u'circles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'circles', 'users', ['user_id'], ['id'])
    op.drop_column(u'users', 'profile_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('profile_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'circles', type_='foreignkey')
    op.drop_column(u'circles', 'user_id')
    op.drop_table('friends_circles')
    # ### end Alembic commands ###
