"""empty message

Revision ID: 4d21c99e9f30
Revises: 4a491d37f055
Create Date: 2018-04-06 13:17:21.355479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d21c99e9f30'
down_revision = '4a491d37f055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'friends', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column(u'friends', sa.Column('fb_profile', sa.String(), nullable=True))
    op.add_column(u'friends', sa.Column('insta_profile', sa.String(), nullable=True))
    op.add_column(u'friends', sa.Column('linkedin_profile', sa.String(), nullable=True))
    op.add_column(u'friends', sa.Column('notes', sa.String(), nullable=True))
    op.add_column(u'friends', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.add_column(u'friends', sa.Column('twitter_profile', sa.String(), nullable=True))
    op.alter_column(u'friends', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'friends', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column(u'friends', 'twitter_profile')
    op.drop_column(u'friends', 'phone_number')
    op.drop_column(u'friends', 'notes')
    op.drop_column(u'friends', 'linkedin_profile')
    op.drop_column(u'friends', 'insta_profile')
    op.drop_column(u'friends', 'fb_profile')
    op.drop_column(u'friends', 'birthday')
    op.drop_table('dates')
    # ### end Alembic commands ###
