"""empty message

Revision ID: 573777f767d4
Revises: 4d21c99e9f30
Create Date: 2018-04-15 15:30:40.718823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573777f767d4'
down_revision = '4d21c99e9f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('job', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('friends', 'job')
    # ### end Alembic commands ###
