"""empty message

Revision ID: 6e4e6a891970
Revises: 063d6797660d
Create Date: 2018-04-23 19:21:05.184810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4e6a891970'
down_revision = '063d6797660d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'image_url')
    # ### end Alembic commands ###
