"""empty message

Revision ID: a70444733230
Revises: 
Create Date: 2018-02-21 17:08:53.993036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70444733230'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('location', sa.String(), nullable=True))
    op.add_column('friends', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'friends', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_column('friends', 'user_id')
    op.drop_column('friends', 'location')
    # ### end Alembic commands ###
