"""empty message

Revision ID: bc49170a940f
Revises: 11b803446327
Create Date: 2018-02-12 12:46:39.743360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc49170a940f'
down_revision = '11b803446327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circles', sa.Column('circle_name', sa.String(), nullable=False))
    op.add_column('circles', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'circles', 'circles', ['parent_id'], ['id'])
    op.add_column('friends', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('friends', 'name')
    op.drop_constraint(None, 'circles', type_='foreignkey')
    op.drop_column('circles', 'parent_id')
    op.drop_column('circles', 'circle_name')
    # ### end Alembic commands ###
